table/urls.py
from django.urls import path
from . import views
from .views import TableApiView

urlpatterns = [
    path('', views.table_list, name='index'),
    path('api/', TableApiView.as_view()),
]

table_app/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('table.urls')),
]

table/models.py
from django.db import models


class Table(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=100)
    count = models.IntegerField()
    distance = models.IntegerField()


    class Meta:
        verbose_name = 'Таблица'
        verbose_name_plural = 'Таблицы'

    def __str__(self):
        return self.name

table/forms.py
from django import forms
from .models import Table


class SortForm(forms.Form):
    tables = Table.objects.all()
    ordering = forms.TypedChoiceField(label='Сортировать:', choices=[('name', 'По названию'),
                                                                     ('count', 'По количеству'),
                                                                     ('distance', 'По расстоянию')])


class ColumnForm(forms.Form):
    tables = Table.objects.all()
    column = forms.TypedChoiceField(label='Сортировать:', choices=[('name', 'По названию'),
                                                                   ('count', 'По количеству'),
                                                                   ('distance', 'По расстоянию')])


class ConditionForm(forms.Form):
    tables = Table.objects.all()
    condition = forms.TypedChoiceField(label='Условие:', choices=[('equals', 'Равно'),
                                                                  ('contains', 'Содержит'),
                                                                  ('over', 'Больше'),
                                                                  ('less', 'Меньше')])


class ValueForm(forms.Form):
    tables = Table.objects.all()
    value = forms.CharField(label='Значение:', widget=forms.TextInput)

table/views.py
from django.shortcuts import render
from rest_framework import generics
from django_filters.rest_framework import DjangoFilterBackend

from .models import Table
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .serializers import TableSerializer
from .forms import SortForm, ColumnForm, ConditionForm, ValueForm



def table_list(request):
    tables = Table.objects.all()

    form = SortForm(request.GET)
    if form.is_valid():
        if form.cleaned_data['ordering']:
            tables = tables.order_by(form.cleaned_data['ordering'])
            for table in tables:
                if form == "name":
                    tables = tables.order_by("name")
                elif form == "count":
                    tables = tables.order_by("count")
                elif form == "distance":
                    tables = tables.order_by("distance")

    page = request.GET.get('page')
    paginator = Paginator(tables, 5)
    try:
        tables = paginator.page(page)
    except PageNotAnInteger:
        tables = paginator.page(1)
    except EmptyPage:
        tables = paginator.page(paginator.num_pages)

    return render(request, 'index.html', {'page': page,'tables': tables, })


class TableApiView(generics.ListCreateAPIView):
    queryset = Table.objects.all()
    serializer_class = TableSerializer

table/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
</head>
<body>
    <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h1>Таблица</h1>
          <form action="" method="GET">
            <select class="form-control input-sm" name="ordering" id="id_ordering" onchange='this.form.submit()'>
            <option disabled selected>Сортировка</option>
            <option value="name">Название</option>
            <option value="count">Количество</option>
            <option value="distance">Расстояние</option>
            </select>
            <noscript><input type="submit" value="Submit"></noscript>
            </form>

        <table class="table table-hover">
          <thead>
            <tr>
              <th scope="col">Дата</th>
              <th scope="col">Название</th>
              <th scope="col">Количество</th>
              <th scope="col">Расстояние</th>
              <th></th>
            </tr>
          </thead>
                {% for table in tables  %}
                    <tbody>
                        <td>{{ table.date }}</td>
                        <td>{{ table.name }}</td>
                        <td>{{ table.count }}</td>
                        <td>{{ table.distance }}</td>
                        </tbody>
                {% endfor %}
        </table>
                <div class="row">
                    {% include 'sorting.html' %}
                </div>
                    <br><br>

            {% include 'pagination.html' with page=tables %}

      </div>
    </div>
    </div>



</body>
</html>

table/templates/pagination.html
<nav aria-label="Page navigation">
<ul class="pagination">
  {% if page.has_previous %}
    <li class="page-item"><a class="page-link" href="?page={{ page.previous_page_number }}">Previous</a></li>
  {% endif %}
    <span class="current">
  <li class="page-item active"><a class="page-link"><span class="sr-only">Page {{ page.number }} of {{ page.paginator.num_pages }}</span></a></li>
    </span>
  {% if page.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page.next_page_number }}">Next</a></li>
  {% endif %}
  </span>
</div>

table/templates/sorting.html
<form action="" method="GET">
  <select class="form-control input-sm" name="column" id="id_column" onchange='this.form.submit()'>
      <option disabled selected>Выберите колонку для фильтрации</option>
      <option value="name">Название</option>
      <option value="count">Количество</option>
      <option value="distance">Расстояние</option>
  </select>
    <select class="form-control input-sm" name="condition" id="id_condition" onchange='this.form.submit()'>
        <option disabled selected>Условие</option>
        <option value="equals">равно</option>
        <option value="contains">содержит</option>
        <option value="over">больше</option>
        <option value="less">меньше</option>
    </select>

    <input type="text" class="form-control input-sm" name="q"  onchange='this.form.submit()' placeholder="Значения для фильтрации" value="" >

    <noscript><input type="submit" value="Submit"></noscript>
</form>